### ISSUE TITLE
Install Plugins View : Search/filter plugins

### ISSUE THREAD

**Issue by epheterson** [KraigM/HomeBridgeController#1]
If I know the name of the plugin I want to add, it'd be nice to filter for it and have only items matching my filter show up in the list. Saves from scrolling and searching :)

**Comment by KraigM** [comment]
Def will do.  When I started that feature, I didn't realize exactly how many homebridge plugins there were :smile:.  If only npm exposed their search functionality, I would hook it directly into that.  Unfortunately they do not yet (/facepalm).  But for now I can at least do a quick name search.

**Comment by KraigM** [comment]
Complete and will be released in version 0.4.0
