### ISSUE TITLE
Add the ability to view the HomeBridge logs

### ISSUE THREAD

**Issue by KraigM** [KraigM/HomeBridgeController#11]
There are several times I have wanted to be able to view the homebridge logs without having to mess with redirecting the logs when starting up homebridge, ssh'ing into my RPi, and viewing the files with nano or tail.  

I would much rather just open up the app and scroll through the logs or old logs.

It would be really awesome to live update the current logs, to watch the logs as I'm messing with HomeKit.

**Comment by KraigM** [comment]
This would really help developers but it would also really help users properly document any issues they are having with HomeBridge

**Comment by tonesto7** [comment]
I was just coming here to open up this exact request :)

**Comment by KraigM** [comment]
Ok so obviously I have been doing some things ^ lol (even more on the app side). I actually have full live logs streaming to the client (its pretty awesome).

So I was trying to make a nice seamless logging that streams the live logs to the client, however I ran into a design conundrum that I thought I would pose to you guys.  Right now it loads the entire day's log and starts streaming from there. But do we need logs from previous days available for download and if so where to put the logs from previous days? (see screenshot below)

<img width="953" alt="screen shot 2016-03-16 at 11 31 43 pm" src="https://cloud.githubusercontent.com/assets/7624028/13836569/ecc7a020-ebd0-11e5-9f33-7302477b3394.png">

**Comment by KraigM** [comment]
Guess I will stick with live only for now

**Comment by KraigM** [comment]
Complete and will be in the next release (0.5.0)
