### ISSUE TITLE
HomeBridgeController Crashing Homebridge on start

### ISSUE THREAD

**Issue by tonesto7** [KraigM/HomeBridgeController#18]
'Error: The requested platform 'HomeBridgeControllerLink' was not registered by any plugin.
Feb 15 19:54:08 HomeBridge homebridge[1012]: at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:88:13)
Feb 15 19:54:08 HomeBridge homebridge[1012]: at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:194:45)
Feb 15 19:54:08 HomeBridge homebridge[1012]: at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:35:36)
Feb 15 19:54:08 HomeBridge homebridge[1012]: at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:23:16)
Feb 15 19:54:08 HomeBridge homebridge[1012]: at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Feb 15 19:54:08 HomeBridge homebridge[1012]: at Module._compile (module.js:410:26)
Feb 15 19:54:08 HomeBridge homebridge[1012]: at Object.Module._extensions..js (module.js:417:10)
Feb 15 19:54:08 HomeBridge homebridge[1012]: at Module.load (module.js:344:32)
Feb 15 19:54:08 HomeBridge homebridge[1012]: at Function.Module._load (module.js:301:12)
Feb 15 19:54:08 HomeBridge homebridge[1012]: at Function.Module.runMain (module.js:442:10)
Feb 15 19:54:08 HomeBridge homebridge[1012]: at startup (node.js:136:18)
Feb 15 19:54:08 HomeBridge homebridge[1012]: at node.js:966:3'

I have removed the node package, tried downloading from git and installing manually.  Nothing is working.  My only option right now is to remove the platform reference from the config.json
Any suggestions?

**Comment by KraigM** [comment]
There should be another error above it. I'm guessing you might have the same issue someone else reported last night. 

There seems to be some issue with some people's npmi package (dependency of homebridge-controller link) not updating and/or not installing all dependencies. 

First make sure the npmi dependency is in the plugin modules.  If not run `npm install` in the plugin dir

Next make sure it is the alpha version of npmi (2.0.1-alpha). If not run `npm install npmi@2.0.1-alpha` in the plugin dir

Next make sure npm is in the node_modules dir of npmi. If not run `npm install` in the npmi dir

**Comment by tonesto7** [comment]
I tried all of those suggestions but nothing is working

**Comment by tonesto7** [comment]
Actually installing npmi worked after completely removing all node packages and physical files.
I had to re-install all homebridge packages and then npmi and now the service startup error went away

**Comment by ghdbwise** [comment]
ERROR LOADING PLUGIN homebridge-controllerlink:
Error: Cannot find module 'npmi/node_modules/npm'

will come up when starting homebridge.
Everything was fine before installing homebridgeController.

After deleting platform ... from config.json. homebridge started again with error hint:

# 

ERROR LOADING PLUGIN homebridge-controllerlink:
Error: Cannot find module 'npmi/node_modules/npm'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-controllerlink/lib/npm.js:28:32)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-controllerlink/lib/plugins.js:5:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
 ====================

After
   sudo npm uninstall homeBridgeController
same messages as before.

After
   sudo npm rebuild
still the same

ERROR LOADING PLUGIN homebridge-controllerlink:
Error: Cannot find module 'npmi/node_modules/npm'
    at Function.Module._resolveFilename (module.js:339:15)

But homebridge can be started and is functional.

**Comment by KraigM** [comment]
I guess Im going to take out the optimization I added.  The npm dependency takes a while to install and it needed npm twice (once for npmi and once for the plugin) and it was rebuilding each one.  But given it works for some and not others, I'm just going to go back to the slower installs

Unless anyone else knows some npm voodoo I can do instead?

**Comment by KraigM** [comment]
Please try out _homebridge-controllerlink 0.3.4_.  I went back to standard dependencies so hopefully it will fix your issues.  Please let me know :+1:

**Comment by ghdbwise** [comment]
Hi, just tried the new version. HomeBridge came up and is running on my RPi2. So the previously noticed error is gone.
Now i'm going to test your App on the Mac. Coming back soon.

**Comment by KraigM** [comment]
Closing this since it seems to have worked for you.  Let me know if I need to reopen

**Comment by KraigM** [comment]
Released in homebridge-controllerlink 0.3.4

**Comment by sirocket** [comment]
Having a similar issue unfortunately on OSX El Capitan, but during the installation process. 

When having the usr/local/lib/node_modules directory open I can see the homebridge-controller folder being created but when I receive the error at the end of installation, the folder ends up getting deleted and the node_modules directory gets reverted as if homebridge-controller never installed.

I do have npmi and npm directories in the usr/local/lib/node_modules directory and npm is inside the nmpi/node_modules directory.

Any help would be appreciated as I would love to use your plugin :)  

![screenshot2](https://cloud.githubusercontent.com/assets/27328206/24941004/d3c43de0-1efb-11e7-9b86-e4ba7a9b71d6.png)

![screenshot1](https://cloud.githubusercontent.com/assets/27328206/24941000/cb249ac2-1efb-11e7-9fb7-7f619438c0bb.png)
