### ISSUE TITLE
Install Plugins View : Detect which plugins are installed and filter from list

### ISSUE THREAD

**Issue by epheterson** [KraigM/HomeBridgeController#2]
If I already have `homebridge-cmd` installed, I don't want to go here to install it. 

It'd be nice if the plugins either don't show up, or show up and say it's already installed (also showing an update button, when necessary).

**Comment by KraigM** [comment]
Agreed.  

Do you think we should keep plugins that need to be updated?  Honestly it would be easier not to, but thought I would throw the question out there

**Comment by epheterson** [comment]
Personally, I think the list should exclude anything already installed.

Though, this is not how the App Store works, which shows placeholders that say [ Installed ]

So, I guess I'm actually not 100% either way.

**Comment by KraigM** [comment]
Implemented and will be in next release (0.3.0)
