### ISSUE TITLE
Full installation of HomeBridge via the app

### ISSUE THREAD

**Issue by KraigM** [KraigM/HomeBridgeController#20]
Setup a way for the HomeBridge server to be installed using the app or some sort of install package.

**Comment by simonrb2000** [comment]
That would be handy.

**Comment by KraigM** [comment]
Added a rough version for RPi and local install on Mac.  Both fully install, setup, configure, and setup autostart.  The RPi version currently installs directly to an SD card and it installs automatically without any interaction.

Definitely room for improvement but a LOT of work has been put into this and it is definitely a lot easier of an installation.

**Comment by KraigM** [comment]
Completed and will be in the next version (0.7.0)
