### ISSUE TITLE
How to use when installed new plugin manually

### ISSUE THREAD

**Issue by tvillingett** [KraigM/HomeBridgeController#23]
Hi,
right now my setup on RPi need to be "sudo npm install ....", but it can run homebridge as the "pi" user.
This means that it fails to install plugins from inside the interface.
So now I install the plugins by hand from ssh to the RPi, is there a way I reload the homebridge setup without restarting the HomeBridgeController?

**Comment by KraigM** [comment]
Does running homebridge with sudo fix the issue?

**Comment by tvillingett** [comment]
Yes, it did!
I copied the settings from the home/pi/.homebridge to root/.homebridge
