### ISSUE TITLE
Notify user when no hubs are currently available

### ISSUE THREAD

**Issue by AppleTechy** [KraigM/HomeBridgeController#27]
Current when no Homebridge process is found it just displays a blank screen. It would be nice if it displays some sort of error message. I think it would look cleaner if it wasn't a popup error but rather inline on the same windows that if a homebridge process was found would be displayed on.
![Currently Displayed](https://cloud.githubusercontent.com/assets/16282786/13714926/db84f0d8-e78e-11e5-910d-9e66ab568a96.png)
![Where I think it would look good to put the error](https://cloud.githubusercontent.com/assets/16282786/13715009/60fd717c-e78f-11e5-91e9-5d01488b36e8.png)

**Comment by KraigM** [comment]
Completed and will be in next release (0.6.0)
