### ISSUE TITLE
Add a "Name" field

### ISSUE THREAD

**Issue by AppleTechy** [KraigM/HomeBridgeController#30]
Currently if you have multiple accessories that use the CMD plugin they only show as CMD. It would be nice if there was either a rename capability or the option to add a "Name" Next to the CMD plugin. This way accesories in you Config can be more accurately described for what they do.
![What it currently displays](https://cloud.githubusercontent.com/assets/16282786/13835303/d408fe70-ebb3-11e5-9929-60ec566b3ece.png)

**Comment by KraigM** [comment]
Given the property "name" is already integrated into homebridge I think I will just reuse that (if provided).

Do you think it is necessary if there is only one (like OnkyoAVR in your screenshot)?

**Comment by KraigM** [comment]
Complete and will be in next release (0.5.0)
