### ISSUE TITLE
Log Homebridge crashes

### ISSUE THREAD

**Issue by AppleTechy** [KraigM/HomeBridgeController#31]
It would be nice if the controller app can log any homebridge crashes and show the uptime of the process before it crashed along with the exact error message that was given when it crashed. This way it would make it easier to try and determine the rooted cause behind errors. This would still allow the user to have homebridge that is always running but still allow for debugging of errors without having to scroll through pages of the log looking for the moment it crashed. Thanks!

**Comment by KraigM** [comment]
When the time comes for #11, you will have to try it out and see if it meets some of these needs or if it can be updated to handle some of this

**Comment by KraigM** [comment]
From the looks of it, the new logger is not capturing crash logs.  We also need it to log closing for any other reason (that way we know it stopped because it shutdown on purpose).  

I also the idea of the notifications but that part should prob be a diff item.  Do you mind splitting that off @AppleTechy ?

**Comment by AppleTechy** [comment]
Nope. I will rename this and create another "issue" for the notification part.

**Comment by KraigM** [comment]
Correct

**Comment by KraigM** [comment]
@AppleTechy What do you think about it auto restarting when it crashes? (thanks to #16 :smile:)

**Comment by AppleTechy** [comment]
Sounds good to me. That makes sense to have it restart when it crashes but would prefer if that was an option toggle on/off function. Though I think that may emphasize the need for it to be able log the time of the crash as well if possible the error that was given that caused the crash so the culprit plugin can be tracked down.

**Comment by KraigM** [comment]
I set it up to auto restart but only if the link setup was successful and it wasn't explicitly disabled in the link's config

**Comment by KraigM** [comment]
Completed and will be in next release 0.6.0
