### ISSUE TITLE
Ability to Change Between Different Homebridge Instance w/out Restart

### ISSUE THREAD

**Issue by AppleTechy** [KraigM/HomeBridgeController#34]
Currently when wanting to switch between different homebridge instances you must restart the application to then connect to the newest hub. If you want to switch back to interacting with the first instance you have to repeat the entire process which can become annoying when dealing with numerous times in a row. Therefore the ability for it to be constantly looking for homebridge instances even after already connecting to one would then allow for the switch between homebridge instances without a restart. Alongside this would be the ability for Homebridge controller to save the pairing pins assigned to different homebridge instances.

**Comment by KraigM** [comment]
It should already be storing pins for you (as long as your hubs have different usernames).

**Comment by AppleTechy** [comment]
Alright I haven't tried that yet as it is a pain to switch between homebridge instances I have limited it to only doing it once. :p

**Comment by KraigM** [comment]
So I will prob make a "Switch Hubs" menu item that will take you back to the first screen.

Should closing the window also you back?  Im kinda going back and forth on that one.

**Comment by KraigM** [comment]
On second thought, I like the idea of "Close" closing the hub as well as the window.  Then when you click on the app or on "Open", you will be back on the main screen.  Still going to keep it as one at a time for now. 

Thoughts?

**Comment by AppleTechy** [comment]
Seems good to me... That would make logical sense to do it that way. The
menu would probably be nice as a refinement later on but I don't think both
ways(hub menu or closing the window) are nessscary at this time.

**Comment by KraigM** [comment]
Complete and will be in the next release (0.6.0)
