### ISSUE TITLE
Version number fails to encode and/or decode when in country that uses commas for decimals

### ISSUE THREAD

**Issue by edelmaca** [KraigM/HomeBridgeController#35]
Hello, I've installed the latest Controller App on my Mac and the Latest plugin on my Pi. The Plugin is implemented into the config.json and is starting up without errors. It is visible in the Controller on my Mac. But as soon as i klick on the HomeBridge within the GUI, this Message Pops up.

"Upgraded Plugin Required
You must install at least version 0.4.0 of the homebridge-controllerlink plugin."

<img width="650" alt="bildschirmfoto 2016-03-24 um 12 38 17" src="https://cloud.githubusercontent.com/assets/17590674/14015993/6c2b802e-f1bd-11e5-9962-7275f0ecaa7f.png">

As Mentioned above, i have installed the latest Plugin which is 0.5.0
All my other HomeBridge devices work like always and are responding the same as before i installed HomeBridgeController.
Any suggestions?

**Comment by AppleTechy** [comment]
You need to update the controller plugin. `npm update -g
homebridge-controllerlink`

**Comment by edelmaca** [comment]
Thanks for the reply but i have the latest version. Of course i tried to update it after your reply. But that hasn't solved the problem. The message is the same after the "update" and reboot of my Pi and HomeBridge. 
PS: I installed the Plugin this morning. So i can't have an older version. It always downloads the latest one.

**Comment by KraigM** [comment]
I assume you restarted the homebridge after installing?

Also find it in [BonjourBrowser](http://www.macupdate.com/app/mac/13388/bonjour-browser) 

Should look something like 
<img width="272" alt="messages image 3928471321" src="https://cloud.githubusercontent.com/assets/7624028/14023009/69093f1a-f1b0-11e5-8f19-75305de9d3a4.png">

**Comment by edelmaca** [comment]
I rebooted the Pi and started HomeBridge after the first installation and after the "update".
I found this one with the BonjourBrowser.
<img width="322" alt="bildschirmfoto 2016-03-24 um 17 48 14" src="https://cloud.githubusercontent.com/assets/17590674/14024581/1326bf02-f1ea-11e5-8a17-8436d33223fe.png">

Does the HomeBridge Version have something to do with that?

**Comment by KraigM** [comment]
Oh I might know what it is,  what version of HomeBridgeController are you using?  Check for updates

**Comment by edelmaca** [comment]
As you can see above, I'm using HomebridgeController 0.5.0, the same as you and it is the newest version. I can't get a newer one, not on my pi and not on my Mac. On both devices I'm using the latest update. 
Controller: 0.5.0
Plugin: 0.5.0

**Comment by KraigM** [comment]
Well it uses that link version property to figure that out.  So if the app is 0.5.0 and the link is 0.5.0... 

Maybe reinstall the app?

**Comment by edelmaca** [comment]
I did that too. 😟 
I even tried it on another Mac. I got the same message.

**Comment by AppleTechy** [comment]
Is your homebridge up to date? If so maybe rerun `npm install -g
homebridge-controllerlink`

**Comment by edelmaca** [comment]
My homebridge is on 0.3.1, the newest is 0.3.2. I will try to update it. I hope this will fix my problem. 

Edit: I tried it to update homebridge, it always stays on 0.3. everything i tried isn't working. i don't know what i can do now. I guess i have to skip this plugin/tool.
As long as my Homebridge is doing fine without it, i´m good.

**Comment by KraigM** [comment]
@edelmaca Try version 0.5.1 of the app.  If that doesn't work, I will dig through the code and figure it out

**Comment by KraigM** [comment]
Actually scratch that, I will go ahead and release version 0.6.0.  I added a message to specify what version the controller thinks your plugin is on

**Comment by edelmaca** [comment]
Ok, thanks. I will try that out as soon as possible. 

Edit: I give it up. i have updated the Controller and the Plugin. Now i´m on 0.6.0 and the Controller says i´m currently on version 60?!
<img width="652" alt="bildschirmfoto 2016-03-28 um 11 45 00" src="https://cloud.githubusercontent.com/assets/17590674/14075594/bb241c16-f4da-11e5-99fe-139845734060.png">

**Comment by KraigM** [comment]
OH WAIT.  Are you from a country that uses commas as decimal points? (i.e. 19,5 degrees outside lol)

**Comment by edelmaca** [comment]
Yes, i´m from Germany.

**Comment by KraigM** [comment]
Ok I bet something is messing up the conversion. I will figure out how to get that fixed prob this week or weekend

**Comment by edelmaca** [comment]
Perfect. Thank you!

**Comment by KraigM** [comment]
Should be fixed by updating the app to 0.6.2.  It was an issue when the app was reading the version info via Bonjour. 

I was able to set my culture for the app to Germany and reproduce the issue with 0.6.1 but not with 0.6.2.  

Please try it out and let me know :smile:

**Comment by edelmaca** [comment]
Well done. 👍🏼 it is working now. 
Thanks for your work on that problem.

**Comment by KraigM** [comment]
HUZZAH! Glad it's working now. I really want to make this compatible with everyone. 

Speaking of, I assume your native language is not English? Any chance I might be able to convince you to help with localization of the app (changing the app to support multiple languages) in the near future?
