### ISSUE TITLE
Error When Running Node 5.9.1

### ISSUE THREAD

**Issue by AppleTechy** [KraigM/HomeBridgeController#36]
I have a "process out of memory error" when running node 5.9.1 and trying to run the link plugin. I have attached the log below. When I removed the controllerlink from the config.json it started working again. I found online others seemed to encounter similar issues using node version 5.70+( [Click here](https://github.com/nodejs/node/issues/5469))

> Last login: Thu Mar 24 21:31:53 on ttys000
> appletechy:~ appletechy$ DEBUG=\* homebridge -D
> [3/24/2016, 9:33:27 PM] Loaded plugin: homebridge-cmd
> [3/24/2016, 9:33:27 PM] Registering accessory 'homebridge-cmd.CMD'
> [3/24/2016, 9:33:27 PM] ---
> [3/24/2016, 9:33:27 PM] Loaded plugin: homebridge-controllerlink
> [3/24/2016, 9:33:27 PM] Registering platform 'homebridge-controllerlink.HomeBridgeControllerLink'
> [3/24/2016, 9:33:27 PM] ---
> [3/24/2016, 9:33:27 PM] Loaded plugin: homebridge-harmonyhub
> [3/24/2016, 9:33:27 PM] Registering platform 'homebridge-harmonyhub.HarmonyHub'
> [3/24/2016, 9:33:27 PM] ---
> [3/24/2016, 9:33:27 PM] Loaded plugin: homebridge-liftmaster
> [3/24/2016, 9:33:27 PM] Registering accessory 'homebridge-liftmaster.LiftMaster'
> [3/24/2016, 9:33:27 PM] ---
> [3/24/2016, 9:33:28 PM] Loaded plugin: homebridge-nest
> [3/24/2016, 9:33:28 PM] Registering platform 'homebridge-nest.Nest'
> [3/24/2016, 9:33:28 PM] ---
> [3/24/2016, 9:33:28 PM] Loaded plugin: homebridge-onkyo-avr
> [3/24/2016, 9:33:28 PM] Registering accessory 'homebridge-onkyo-avr.OnkyoAVR'
> [3/24/2016, 9:33:28 PM] ---
> [3/24/2016, 9:33:28 PM] Loaded plugin: homebridge-platform-wemo
> [3/24/2016, 9:33:28 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
> [3/24/2016, 9:33:28 PM] ---
> [3/24/2016, 9:33:28 PM] Loaded plugin: homebridge-wink
> [3/24/2016, 9:33:28 PM] Registering platform 'homebridge-wink.Wink'
> [3/24/2016, 9:33:28 PM] ---
> [3/24/2016, 9:33:28 PM] Loaded config.json with 7 accessories and 5 platforms.
> [3/24/2016, 9:33:28 PM] ---
> [3/24/2016, 9:33:28 PM] Loading 5 platforms...
> [3/24/2016, 9:33:28 PM] Initializing Nest platform...
> [3/24/2016, 9:33:28 PM] Fetching Nest devices.
> [3/24/2016, 9:33:28 PM] [WeMo Platform] Initializing BelkinWeMo platform...
> [3/24/2016, 9:33:28 PM] [Wink] Initializing Wink platform...
> [3/24/2016, 9:33:28 PM] [Wink] Fetching Wink devices.
>   wink:http http options +0ms { hostname: 'winkapi.quirky.com',
>   port: 443,
>   path: '/oauth2/token',
>   method: 'POST',
>   headers: { 'Content-Length': 175, 'Content-Type': 'application/json' } }
>   wink:http http data +15ms { host: 'winkapi.quirky.com',
>   path: '/oauth2/token',
>   data: '{"client_id":"[Removed]","client_secret":"[removed]","username":"[removed]","password":"[removed]","grant_type":"password"}',
>   method: 'POST' }
> [3/24/2016, 9:33:28 PM] [Harmony Hub] Initializing HarmonyHub platform...
> [3/24/2016, 9:33:28 PM] [Harmony Hub] Searching for Logitech Harmony remote hubs...
>   harmonyhubjs:discover:explorer Explorer(61991) +0ms
>   harmonyhubjs:discover:ping Ping(61991) +1ms
>   harmonyhubjs:discover:explorer start() +1ms
>   harmonyhubjs:discover:responsecollector ResponseCollector(61991) +0ms
>   harmonyhubjs:discover:responsecollector start() +1ms
>   harmonyhubjs:discover:ping start() +0ms
> [3/24/2016, 9:33:28 PM] Initializing HomeBridgeControllerLink platform...
>   express:application set "x-powered-by" to true +0ms
>   express:application set "etag" to 'weak' +1ms
>   express:application set "etag fn" to [Function: wetag] +1ms
>   express:application set "env" to 'development' +0ms
>   express:application set "query parser" to 'extended' +0ms
>   express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
>   express:application set "subdomain offset" to 2 +0ms
>   express:application set "trust proxy" to false +0ms
>   express:application set "trust proxy fn" to [Function: trustNone] +1ms
>   express:application booting in development mode +1ms
>   express:application set "view" to [Function: View] +0ms
>   express:application set "views" to '/Users/appletechy/views' +1ms
>   express:application set "jsonp callback name" to 'callback' +0ms
>   express:router use / query +11ms
>   express:router:layer new / +1ms
>   express:router use / expressInit +0ms
>   express:router:layer new / +1ms
>   express:router use / jsonParser +1ms
>   express:router:layer new / +0ms
>   express:router:route new /plugins +0ms
>   express:router:layer new /plugins +1ms
>   express:router:route get /plugins +0ms
>   express:router:layer new / +0ms
>   express:router:route new /plugins +0ms
>   express:router:layer new /plugins +1ms
>   express:router:route post /plugins +0ms
>   express:router:layer new / +0ms
>   express:router:route new /plugins/available +0ms
>   express:router:layer new /plugins/available +0ms
>   express:router:route get /plugins/available +0ms
>   express:router:layer new / +0ms
>   express:router:route new /config +0ms
>   express:router:layer new /config +0ms
>   express:router:route get /config +0ms
>   express:router:layer new / +0ms
>   express:router:route new /config +1ms
>   express:router:layer new /config +0ms
>   express:router:route post /config +0ms
>   express:router:layer new / +0ms
>   express:router:route new /hub +0ms
>   express:router:layer new /hub +0ms
>   express:router:route get /hub +0ms
>   express:router:layer new / +0ms
>   express:router:route new /hub +0ms
>   express:router:layer new /hub +0ms
>   express:router:route post /hub +0ms
>   express:router:layer new / +0ms
>   express:router:route new /install/status +0ms
>   express:router:layer new /install/status +1ms
>   express:router:route get /install/status +0ms
>   express:router:layer new / +0ms
>   express:router:route new /ping +0ms
>   express:router:layer new /ping +0ms
>   express:router:route get /ping +0ms
>   express:router:layer new / +0ms
>   express:router use /log/live <anonymous> +0ms
>   express:router:layer new /log/live +2ms
>   express:router use /log <anonymous> +0ms
>   express:router:layer new /log +0ms
>   express:router use / router +0ms
>   express:router:layer new / +0ms
>   express:router:route new /log +0ms
>   express:router:layer new /log +0ms
>   express:router:route get /log +0ms
>   express:router:layer new / +0ms
> [3/24/2016, 9:33:28 PM] Loading 7 accessories...
> [3/24/2016, 9:33:28 PM] [ Single Bay Garage Door] Initializing LiftMaster accessory...
> [3/24/2016, 9:33:28 PM] [ Main Garage Door] Initializing LiftMaster accessory...
> [3/24/2016, 9:33:28 PM] [FR Onkyo Reciever] Initializing OnkyoAVR accessory...
> [3/24/2016, 9:33:28 PM] [FR Onkyo Reciever] start long poller..
> [3/24/2016, 9:33:28 PM] [History Channel] Initializing CMD accessory...
> [3/24/2016, 9:33:28 PM] [Food Network] Initializing CMD accessory...
> [3/24/2016, 9:33:28 PM] [Discovery Channel] Initializing CMD accessory...
> [3/24/2016, 9:33:28 PM] [News] Initializing CMD accessory...
> [3/24/2016, 9:33:28 PM] [WeMo Platform] Server Listening...
>   socket.io:server initializing namespace / +62ms
>   socket.io:server creating engine.io instance with opts {"path":"/socket.io"} +1ms
>   socket.io:server attaching client serving req handler +3ms
> <--- Last few GCs --->
>    12739 ms: Mark-sweep 1403.7 (1439.2) -> 1403.9 (1441.2) MB, 52.5 / 0 ms [last resort gc].
>    12754 ms: Scavenge 1406.4 (1441.2) -> 1406.4 (1441.2) MB, 8.4 / 0 ms [allocation failure].
>    12760 ms: Scavenge 1406.4 (1441.2) -> 1406.4 (1441.2) MB, 4.5 / 0 ms [allocation failure].
>    12813 ms: Mark-sweep 1406.4 (1441.2) -> 1406.4 (1441.2) MB, 52.5 / 0 ms [last resort gc].
>    12874 ms: Mark-sweep 1406.4 (1441.2) -> 1406.4 (1441.2) MB, 61.5 / 0 ms [last resort gc].
> <--- JS stacktrace --->
> ==== JS stack trace =========================================
> Security context: 0x1fbcf2be3ac1 <JS Object>
>     1: stringify [native json.js:160] [pc=0x3cf4c1b3a8e4](this=0x1fbcf2bdb8a1 <a JSON with map 0x3034ca40a7c9>,u=0x1fbcf2bf8d01 <an Object with map 0x13fbb57e8ef9>,v=0x1fbcf2b04189 <undefined>,I=0x1fbcf2b04189 <undefined)
>     2: arguments adaptor frame: 1->3
>     3: tryStringify(aka tryStringify) [util.js:14] [pc=0x3cf4c1befff1] (this=0x1fbcf2b04189 <undefined>,arg=0x1fbcf2bf8d01 <an Object wi...
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
> Abort trap: 6

**Comment by KraigM** [comment]
Fixed in homebridge-controllerlink 0.6.2
