### ISSUE TITLE
Upload Config : Always keep backup

### ISSUE THREAD

**Issue by epheterson** [KraigM/HomeBridgeController#4]
Since a program is doing the updating anyway, it'd be nice if the previous version, or several previous versions, were maintained on disk in the event the user hit 'Upload Config' by accident and lost stuff.

**Comment by KraigM** [comment]
Good point.  I had thought about keeping a backup simple backup just in case, but I really like the idea of versioning it.

**Comment by KraigM** [comment]
Im thinking about hooking into Mac's document system.  That way we can offload keeping track of the versions, providing ui to revert, proper integration into mac, etc.

**Comment by epheterson** [comment]
Sounds like the best way to go for sure! Do you get version history UI for free as well?

**Comment by KraigM** [comment]
I believe so

**Comment by KraigM** [comment]
From what I understand, I just teach what the UI is for the document and create a custom document type and it pretty much does it from there.  I think the tricky part will be finding a way to integrate it but disable all the active features (install updates, upload, etc).

**Comment by KraigM** [comment]
Completed and will be in next release (0.4.0)

**Comment by KraigM** [comment]
This one was a doozy... 800+ lines of code...

But it works and its pretty awesome :grinning:

**Comment by KraigM** [comment]
Version 0.4.0 has been released
