### ISSUE TITLE
Loading npm info is slow when using a machine like RPi

### ISSUE THREAD

**Issue by KraigM** [KraigM/HomeBridgeController#41]
Unfortunately the npm calls are taxing on RPi (they fully admit their api is slow).  We need to either find a way to optimize the meta info refresh (like just pulling exactly what you need) or we need to move that to the app, or both.

**Comment by AppleTechy** [comment]
As the program is currently running on hardware other than RPIs. I think the best choice would to have the app pull the metadata as we know it has enough processing power to do so along with a better npm api

**Comment by KraigM** [comment]
Complete and will be in the next release (0.7.0)
