### ISSUE TITLE
TypeError: undefined is not a platform

### ISSUE THREAD

**Issue by david-loadman** [KraigM/HomeBridgeController#43]
I recently installed the plugin using sudo npm -g...., edited the config.json file to add the platform and when home bridge starts I get the following error:

> Initializing HomeBridgeControllerLink platform....
> /usr/local/node_modules/homebridge-controllerlink/lib/logger.js:83
>           var breakline = (c + ' ').repeat(10);
>                                               |
> TypeError: undefined is not a function
>       at getBreakString (/usr/local/lib/node_modules/homebridge=controllerlink/lib/logger.js:83.28)

Any suggestions would be appreciated.

**Comment by KraigM** [comment]
Looks like you have an old version of node.  I'm about to release a fix for you (0.6.4) that will support older versions of node.  You will have to let me know if anything else pops up on older versions

**Comment by KraigM** [comment]
Released fix in 0.6.4
