### ISSUE TITLE
Fix cut off letters in left column

### ISSUE THREAD

**Issue by epheterson** [KraigM/HomeBridgeController#48]
See screenshot, the g's are cut off, indicating something wonky happening in the UI.
![screen shot 2016-04-16 at 10 39 18 pm](https://cloud.githubusercontent.com/assets/151483/14585307/2ffc5028-0424-11e6-9345-1c1565791f35.png)

**Comment by epheterson** [comment]
If you're addressing UI things, notice how the text can overlap as so :
![screen shot 2016-04-16 at 10 45 18 pm](https://cloud.githubusercontent.com/assets/151483/14585333/f6c2fd88-0424-11e6-8da9-9c0bf85b0435.png)

**Comment by epheterson** [comment]
Another one I found is the shadow on the switches seem to be cut off on the bottom :
![screen shot 2016-04-16 at 10 48 50 pm](https://cloud.githubusercontent.com/assets/151483/14585348/7d7bca12-0425-11e6-96bf-598692259ce1.png)

**Comment by KraigM** [comment]
All fixed and will be in the next release (0.7.0)
