### ISSUE TITLE
Log parsing issue when homebridge started via init script.

### ISSUE THREAD

**Issue by chrisgrande** [KraigM/HomeBridgeController#52]
![image](https://cloud.githubusercontent.com/assets/825577/15569517/3464777c-22ff-11e6-80fb-dcc4e4a17e71.png)

**Comment by KraigM** [comment]
What is happening?  

From the looks of it you are running in full debug mode (with environment variable DEBUG=*) so it is getting the debug logs in the output.  

Unfortunately if socket.io is included in the logs then every log it sends to the client gets logged in full to the "error log" (as to not effect the standard output).  I explicitly don't stream it down live but the log history is pulled directly from the log files.

**Comment by KraigM** [comment]
???

**Comment by chrisgrande** [comment]
Sorry, I didn't have time to get back around to this - I think there was something wrong with my install, I created a new system using your automated SD card creation and I no longer have this problem.
