### ISSUE TITLE
Display Plugin Readme.md in UI

### ISSUE THREAD

**Issue by JangoBritt** [KraigM/HomeBridgeController#54]
On the Add Plugin UI, would it be possible to display the whole Readme.md file? 

The Description field doesn't give a great amount of information as to what the plugin can do, and it's use-cases. Displaying the whole Readme.MD might help with that.

If you can display this in a scrollable memo box, it would be better than switching to safari for each plugin to see the details of what you want to install.

**Comment by KraigM** [comment]
Yeah I definitely agree. I will see about maybe adding it in 0.8.0

**Comment by KraigM** [comment]
Completed and will be in next release (0.8.0)
