### ISSUE TITLE
Controller Link doesn't modify config.json

### ISSUE THREAD

**Issue by JangoBritt** [KraigM/HomeBridgeController#56]
So I've been playing with this, and having a few issues.

When I add a plugin, and related accessory, it doesn't show up in my config.json in the .homebridge folder... Does the Controller Link have it's own sand-boxed config.json that it's using once you restart the hub?

I have installed the particle plugin, and a particle platform (enabled) and yet, it's not showing up on my HomeKit.

Also, I have uninstalled the itunes plugin, but it still shows up as an accessory on my homekit, and the controller logs say it can't find the plugin to match the itunes platform...

Where can I find this second config.json? If I have to have homebridge running before the controller link will allow me to restart a hub (in order to load the sandboxed config.json), do I have to maintain one copy for booting, and then reboot again once controllerlink is open?

**Comment by JangoBritt** [comment]
le Sigh.

Today is a morning of stupid mistakes. Although it highlights a feature request:

when restarting the hub, how about a popup "Do you want to Save Changes to config.json first?"

**Comment by KraigM** [comment]
This was actually asked for not too long ago #46
