### ISSUE TITLE
Disable Platforms/Accessories without losing their configs

### ISSUE THREAD

**Issue by KraigM** [KraigM/HomeBridgeController#7]
This might just be a personal problem (as a homebridge plugin dev), but I am constantly enabling and disabling of plugins for testing.  I have also had cases where I need to disable a platforms that where causing issues (like when the Nest servers went down and it took out everyone's homebridge).

I figure we can use a simple checkbox on the app to move the config to an array that homebridge is not looking for.  That way all your configurations remain in tact, but homebridge will not see them.

**Comment by epheterson** [comment]
When this is implemented, disabled plugins/platforms/accessories should appear disabled or dimmed. Perhaps they should sort into their own area?

**Comment by Chioti** [comment]
+1 This would be great for debugging misbehaving plugins

**Comment by KraigM** [comment]
I can def see the use of both #10 as well as this one (#7), but whats the best way to distinguish between the two?  Really either could be "Enable / Disable" so I'm trying to think through what the best terminology is for each.  Here are some options for either that I thought of:
- Enable / Disable
- On / Off
- Attach / Detach
- Insert / Remove (as opposed to Add / Delete for completely removing it)

Right now I'm leaning towards what is described already on the respective items (#7:Enable/Disable #10:On/Off) but given that I'm still undecided I thought I would get you guys' opinion. Thoughts? Other options?

**Comment by epheterson** [comment]
I think I like enable/disable the best, and perhaps when you hover over the button it can clarify what enable and disable means.

**Comment by KraigM** [comment]
@epheterson So I'm guessing you would want On/Off for #10 (still shows up in HomeKit so it doesn't mess up you Homekit settings but is somehow turned off in HomeBridge)?

**Comment by KraigM** [comment]
Completed and will be in next release (0.5.0)
