### ISSUE TITLE
Unable to delete platform/accessory/plugin

### ISSUE THREAD

**Issue by epheterson** [KraigM/HomeBridgeController#9]
All items in the left column (save the Hub) should be removable with the Delete key. 

All removal operations should prompt the user with Discard / Cancel options.

Deleting platforms/accessories would modify the config.json

Deleting plugins would npm uninstall them. When deleting plugins, the UI should present a list of accessories/platforms that will also be removed with it – ie. the UI should also perform these remove operations on the users' behalf.

**Comment by KraigM** [comment]
Part of that kinda goes along with #7 but yeah it needs actual removals as well

**Comment by KraigM** [comment]
Completed and will be in next release (0.4.0)
